language: elixir
elixir:
- 1.0.0
env:
  matrix:
  - MIX_ENV=test
  global:
    secure: OdTofVXxufS4xt6JBUsd+v4Fxnh9hK8drAIE8YC5kp3N8fAjHg3xTT/J8qlkdCCapOgxeUSbtZixgYNSB1vNhl/mLeOyg2F8hz8HWC2Avr2L7CxyV6Ci9Nv0CC3bC6wRRS8SvNOMznAeQwR8kjHLAQZ0SIJSRD2ZmqMbnUdLk6iQmdrwCQe97TtS5+94qtRzu7wB+ytC4bSEAE6gIYgtmyvqF39QbsB1/31AI8J3Ic86K/HXvKBGaEyTgZmaU59AemhXaSCRun0Vcajk6tylC43lQvzITuzU6V5l664jBofixZtt5vZ4QWJGh3Z8waOhPYBazGEBUXsL47K2G9ktext2M97Qvd+iNpeSRK/uef3OJpjL29XIWLYA7RcfBpardx4avnyrCgcisNpvkOoMkADE/6YEATkv6vXDYtC59JE0Bv28SB6uw3dM+JiVnumjYWNbbwyxuwY2X+SeNXeoSNRhoBqU2/mEOq9jfTFKPE2Tch7Iq06jlNw9/7xfSC7Cille1bsT55+40vmbu/ps6W0lbNZGsXGFR2+iQBrAyKUjN/bdj0eD9brtE5ebjFwSEZfa2cq7rXN+nHnXiLnDaQCmOxCbkNHNe+nBHf+Z0sHuxGClvLPJzbhurLl1xEQq7XDBf3VaF09vUhPtvIob6Nkq1QojMziX8mV3uwsBWaw=
