language: elixir
elixir:
- 1.0.0
env:
  matrix:
  - MIX_ENV=test
  global:
    secure: KHSgvhnHq0DTYaY68edIAJLCOLpga4mLYeamVbYn/VcL+sWeIvRzdospzfKlfip9R/RlEprQBfD3YT5xDhRIkcV9JjoZybQGQQFwjUO+h09Wq31RHJwdymW1cef9z6mNs4ob3+5ErF21e6F73qaprYJY0OcVPdDzbGrayUhQGGIAUtBtVKduByX35kA/NifpoJRrEK6B4gmjj08Fxq2sA4uTUFyXOz7eaecruIvi8RlbB4SMTHBE1GiAzbLgazxK4a8mg40qXWd7MImNTeq7WYZCuVtOyABgil5Pi1wuI2rxQo20iGw7vGlk6UAcnrcBehLNmOBpnxXEC7nW8BQ/hC7cNKQ3kJP2wTzyUaiXmOavzw6h5GdgIkMxI9elMxqh3d/c5iveilFAi5BOjf7Dz3bHJ+uPRh5UERHElru4tz3htbQV7oXaT1RRC4g8Ipco5RYPFNKKkf1KU5wcdElLHVzOU1sRK1XF5u8UKoFax83OwmC6B9GuiSz2M58yBUMUJopGVbvwmJuhk0vAhBU/F5ViZASpVBzmkhoaqSFv8AZMtt/ndXrHPgrMLdraUtcNvl8WctTsFi9Nm2pIpSMmMaMXWS6aRQMRCAgJ2h0IFBOA957d68RU6ux6KKFpqBHy9cSmAK2SBXONNLFkCrT0DLSizc/sZd5InQdEfFp1f2M=
